apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-2404-fastclone-example
  namespace: vm-images
  labels:
    app.kubernetes.io/name: ubuntu-2404-fastclone-example
    qnap.mii.dev/fast-clone-example: "true"
spec:
  storageClassName: qnap-fastclone
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 40Gi
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: golden-ubuntu-2404-snap
