apiVersion: v1
kind: ServiceAccount
metadata:
  name: qnap-fast-clone-controller
  namespace: trident
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qnap-fast-clone-controller
rules:
  - apiGroups:
      - qnap.mii.dev
    resources:
      - qnapfastclones
      - qnapfastclones/status
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
      - volumesnapshotcontents
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - patch
  - apiGroups:
      - ""
    resources:
      - persistentvolumes/status
      - persistentvolumeclaims/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - trident.qnap.io
    resources:
      - tridentvolumes
    verbs:
      - get
      - list
      - create
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qnap-fast-clone-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qnap-fast-clone-controller
subjects:
  - kind: ServiceAccount
    name: qnap-fast-clone-controller
    namespace: trident
